spring:
  application:
    name: Web3 Wallet Backend (prod)
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/wallet_db}
    username: ${DB_USERNAME:wallet}
    password: ${DB_PASSWORD:wallet}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
