spring:
  application:
    name: Web3 Wallet Backend


  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: false   # disable Flyway until you add migration scripts


web3:
  ethereum:
    rpcUrl: https://sepolia.infura.io/v3/a8ce71b1d84d4b2bad66bb01c685926f