spring:
  application:
    name: Web3 Wallet Backend

  datasource:
    url: jdbc:h2:file:./data/wallet_dev
    driver-class-name: org.h2.Driver
    username: ${H2_USERNAME:sa}
    password: ${H2_PASSWORD:password}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

  # Redis configuration for caching
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 60000

  cache:
    type: redis
    redis:
      time-to-live: 300000 # 5 minutes in milliseconds
      cache-null-values: false

# JWT configuration
app:
  jwt:
    secret: ${JWT_SECRET:dGhpc0lzQVNlY3JldEtleUZvcldlYjNXYWxsZXRCYWNrZW5kSldUVG9rZW5TaWduaW5nVGhhdE11c3RCZTBY}
    expiration-ms: ${JWT_EXPIRATION:3600000} # 1 hour

web3:
  ethereum:
    rpcUrl: https://sepolia.infura.io/v3/a8ce71b1d84d4b2bad66bb01c685926f
    chainId: 11155111
